import os
import random
import numpy as np
import torch
from sklearn.model_selection import train_test_split


def seed_everything(seed):
    random.seed(seed)
    os.environ["PYTHONHASHSEED"] = str(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.backends.cudnn.deterministic = True


def text_preprocessing_func(text: str) -> str:
    """
    깨진 문자를 변환하고 특수문자를 삭제하는 함수
    """
    text = text.replace("Ã?Â©️", "e")  # 원래는 é인데 걍 e로 메움
    text = text.replace("Ã©️", "e")
    text = text.replace("Ã?Â?", "e")  # 원래는 é인데 걍 e로 메움
    text = text.lower()
    text = text.replace("ã", "a")
    text = text.replace("\xa0", " ")
    text = text.replace("â", "a")
    text = text.replace("\n", " ")
    text = text.replace("&#39;", "'")
    text = text.replace("&quot;", "")
    text = text.replace("à", "a")
    text = text.replace("--", "-")
    text = re.sub(r"[^a-z\d\- ]", "", text)
    del_list = ["³", "º", "ª", "¼", "µ", "¹", "²", "½"]
    for del_word in del_list:
        text = text.replace(del_word, "")
    text = text.strip()
    return text


country_fix_dict = {
    "usa": {
        "oklahoma",
        "districtofcolumbia",
        "connecticut",
        "worcester",
        "aroostook",
        "texas",
        "kern",
        "orangeco",
        "unitedstatesofamerica",
        "fortbend",
        "alachua",
        "massachusetts",
        "arizona",
        "austin",
        "hawaii",
        "ohio",
        "camden",
        "arkansas",
        "minnesota",
        "losestadosunidosdenorteamerica",
        "us",
        "usanow",
        "northcarolina",
        "maine",
        "colorado",
        "oklahoma",
        "alabama",
        "anystate",
        "districtofcolumbia",
        "unitedstaes",
        "pender",
        "newhampshire",
        "unitedstates",
        "missouri",
        "idaho",
        "ca",
        "newyork",
        "tennessee",
        "stthomasi",
        "dc",
        "washington",
        "illinois",
        "california",
        "michigan",
        "iowa",
        "maryland",
        "newjersey",
        "vanwert",
        "oregon",
    },
    "uk": {
        "alderney",
        "wales",
        "aberdeenshire",
        "bermuda",
        "nottinghamshire",
        "scotland",
        "usacurrentlylivinginengland",
        "england",
        "countycork",
        "alderney",
        "cambridgeshire",
        "middlesex",
        "northyorkshire",
        "westyorkshire",
        "cocarlow",
        "sthelena",
    },
    "japan": {"okinawa"},
    "southkorea": {"seoul"},
    "canada": {
        "ontario",
        "alberta",
        "novascotia",
        "newfoundland",
        "newbrunswick",
        "britishcolumbia",
    },
    "miyanma": {"burma"},
    "newzealand": {"auckland", "nz", "otago"},
    "spain": {
        "andalucia",
        "pontevedra",
        "gipuzkoa",
        "lleida",
        "catalunyaspain",
        "galiza",
        "espaa",
    },
    "germany": {"niedersachsen", "deutschland"},
    "brazil": {"disritofederal"},
    "switzerland": {"lasuisse"},
    "italy": {"veneziagiulia", "ferrara", "italia"},
    "australia": {"nsw", "queensland", "newsouthwales"},
    "belgium": {"labelgique", "bergued"},
    "uruguay": {"urugua"},
    "panama": {"republicofpanama"},
}
country_del_list = [
    "c",
    "space",
    "universe",
    "unknown",
    "quit",
    "tdzimi",
    "universe",
    "tn",
    "unknown",
    "space",
    "c",
    "franciscomorazan",
    "petrolwarnation",
    "ineurope",
    "hereandthere",
    "faraway",
]

isbn_code = {
    "0": "english",
    "1": "english",
    "2": "franch",
    "3": "german",
    "4": "japan",
    "5": "russia",
    "7": "china",
    "65": "brazil",
    "80": "czecho",
    "81": "india",
    "82": "norway",
    "83": "poland",
    "84": "espanol",
    "85": "brazil",
    "86": "yugoslavia",
    "87": "danish",
    "88": "italy",
    "89": "korean",
    "90": "netherlands",
    "91": "sweden",
    "92": "international ngo",
    "93": "inida",
    "94": "netherlands",
    "600": "iran",
    "601": "kazakhstan",
    "602": "indonesia",
    "603": "saudi arabia",
    "604": "vietnam",
    "605": "turkey",
    "606": "romania",
    "607": "mexico",
    "608": "north macedonia",
    "609": "lithuania",
    "611": "thailand",
    "612": "peru",
    "613": "mauritius",
    "614": "lebanon",
    "615": "hungary",
    "616": "thailand",
    "617": "ukraine",
    "618": "greece",
    "619": "bulgaria",
    "620": "mauritius",
    "621": "phillippines",
    "622": "iran",
    "623": "indonesia",
    "624": "sri lanka",
    "625": "turkey",
    "626": "taiwan",
    "627": "pakistan",
    "628": "colombia",
    "629": "malaysia",
    "630": "romania",
    "950": "argentina",
    "951": "finland",
    "952": "finland",
    "953": "croatia",
    "954": "bulgaria",
    "955": "sri lanka",
    "956": "chile",
    "957": "taiwan",
    "958": "colombia",
    "959": "cuba",
    "960": "greece",
    "961": "slovenia",
    "962": "hong kong",
    "963": "hungary",
    "964": "iran",
    "965": "israel",
    "966": "urkaine",
    "967": "malaysia",
    "968": "mexico",
    "969": "pakistan",
    "970": "mexico",
    "971": "phillippines",
    "972": "portugal",
    "973": "romania",
    "974": "thailand",
    "975": "turkey",
    "976": "caribbean community",
    "977": "egypt",
    "978": "nigeria",
    "979": "indonesia",
    "980": "venezuela",
    "981": "singapore",
    "982": "south pacific",
    "983": "malaysia",
    "984": "bangladesh",
    "985": "velarus",
    "986": "taiwan",
    "987": "argentina",
    "988": "hong kong",
    "989": "portugal",
    "9960": "saudi arabia",
    "9963": "cyprus",
    "9968": "costa rica",
    "9971": "singapore",
    "9972": "peru",
    "9974": "uruguay",
    "9976": "tanzania",
    "9977": "costa rica",
    "9979": "iceland",
    "9986": "lithuania",
    "99903": "mauritius",
    "99905": "bolivia",
    "99909": "malta",
    "99912": "botswana",
    "99920": "andorra",
    "99928": "georgia",
    "99935": "haiti",
    "99936": "bhutan",
    "99942": "armenia",
    "99943": "albania",
    "99974": "bolivia",
    "99975": "mongolia",
    "99989": "paraguay",
}

fiction = {
    "fiction",
    "ficti",
    "liter",
    "poem",
    "poetry",
    "novel",
    "sonnet",
    "adventu",
    "comics",
    "graphic novel",
    "drama",
    "myste",
    "thril",
    "suspen",
    "horror",
    "occult",
    "motion pictur",
    "romance",
    "imagin",
    "science fiction",
    "fantasy",
    "fairy",
    "fairies",
    "vampire",
    "epidemic",
    "ghost",
    "alien",
    "supernatural",
    "magic",
    "dragons",
    "elves",
    "angel",
    "devil",
}
unclassified = {
    "crime",
    "murder",
    "criminal",
    "homicide",
    "mafia",
    "gang",
    "drug",
    "short",
}
